repos:
  # Python linter and formatter (https://docs.astral.sh/ruff/)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff # Ruff linter
        args: [--fix]
      - id: ruff-format # Ruff formatter
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v4.0.0-alpha.8"
  #   hooks:
  #     - id: prettier
